### ISSUE TITLE
Bind mocks by constructor

### ISSUE THREAD

**Issue by kkurczewski** [Ninja-Squad/springmockk#104]
Hi, 

currently this project allows to scan fields with `lateinit var` for `@MockkBean` and `@SpykBean` annotations, would you be interested in PR that extends scanning to constructor parameters?

I did a some prototyping and besides changes in `DefinitionsParser` this feature requires [Junit 5ParameterResolver](https://junit.org/junit5/docs/5.0.2/api/org/junit/jupiter/api/extension/ParameterResolver.html) to be implemented as well - not sure if you would want it in the same artifact or as a separate one.

So, what do you say?

**Comment by csikb** [comment]
+1

**Comment by jnizet** [comment]
Sorry for the very very late reply. 
I plan to stick to what the Spring Boot support does for Mockito. Diverging too much from that would potentially introduce new bugs that I don't feel like fixing, and make the job of mirroring the changes that Spring Boot introduces harder.

**Comment by olaisolheim** [comment]
Oh noes, we've (organisation with 100 devs) been waiting for constructor support, as it lends itself to more idiomatic Kotlin.

Please reconsider! 🤞

**Comment by jnizet** [comment]
TBH, I don't use Kotlin very much anymore these days, and I maintain this for free, and on my free time. If you or your company would like to fork this library and take over its maintenance in the future, I'd be happy to archive this repo and make it point to your fork.

I see that the change is not huge, so I might consider integrating it, but it would be nice if you could step up to fix potential bugs, and help me at least concerning this part, in the future, so that it doesn't become a hassle for me.
