### ISSUE TITLE
SpykBean not accepting existing value

### ISSUE THREAD

**Issue by antechrestos** [Ninja-Squad/springmockk#24]
Hi,

I am using your library and am very found of it. I can have the same functionalities I used to have on spring mockito.
However I miss the following one.

Given I want to control some bean that are only use at start time, I used to use `@Spy` annotation to inject a concrete bean of my own in the spring context to replace the normal one (for example injecting a `@ConfigurationProperties` bean).

I cannot achieve this with the `@MockkBean` annotation as, as I wrote, the bean is only read at application start up. 

Thank you

**Comment by jnizet** [comment]
I don't understand what you mean. First, Spy is not a Spring annotation. It's a [Mockito annotation](https://static.javadoc.io/org.mockito/mockito-core/2.28.2/org/mockito/Spy.html), and Spring doesn't care about it. The equivalent with MockK would be the [SpyK annotation](https://mockk.io/#junit5)

If you're actually talking about the Spring [SpyBean](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/mock/mockito/SpyBean.html) annotation, the equivalent is the SpykBean annotation, provided by this library, and working the exact same way as Spring's SpyBean annotation, except of course it uses MockK instead of Mockito.

If you think there's a difference of behavior between Spring's SpyBean and SpringMockK's SpykBean, then please provide a minimal complete example with a Mockito-based test and a SpringMockK-based test that are supposed to be identical but are not.
