### ISSUE TITLE
When verifying MockkBean's, verification acknowledgement fails

### ISSUE THREAD

**Issue by edeesis** [Ninja-Squad/springmockk#27]
I'll preface this by saying that I'm not sure whether this is something that is possible to fix without repercussions.

However, here's the issue:

When using `@MockkBean`, the mock is added to a ConcurrentHashMap. This means that the Object#hashCode method is called whenever that mock is retrieved or placed in the map.

That naturally conflicts with the io.mockk.MockK#confirmVerified method which double checks all recorded calls were first called to verify.

There is a workaround of using io.mockk.MockK#excludeRecords, but considering I'm not the one putting the object in a HashMap, I don't see why I have to add these extra verifies.

**Comment by jnizet** [comment]
Hi @edeesis 

Sorry for the late reply: I was on vacation.

Actually, I think that the map being concurrent is unnecessary because the rest of the Spring testing framework isn't thread-safe anyway. 
And I also think I could replace the ConcurrentHashMap by an IdentityHashMap, which would avoid calling hashCode() and equals() on the mock when storing it in the map.

Could you please provide a minimum test case reproducing a test failure caused by the usage of a ConcurrentHashMap in SpringMockk? That would make sure that switching to an IdentityhashMap indeed fixes your issue.

**Comment by edeesis** [comment]
Hi @jnizet 

Here's the test case that I came up with: https://github.com/edeesis/springmockk-testcase

I noticed while working on it that it only seems to happen when mocking out interfaces interestingly enough. Thanks for your help!

**Comment by jnizet** [comment]
Thanks @edeesis. I've been able to reproduce the issue thanks to your test case. Using an IdentityHashMap fixes it. I've published version 1.1.3 which fixes the issue. It's already available on jcenter, and should be available soon in Maven Central.

**Comment by edeesis** [comment]
Perfect! Thanks for the quick turnaround!
