### ISSUE TITLE
Incorporate into mockk

### ISSUE THREAD

**Issue by pas2al** [Ninja-Squad/springmockk#30]
First of all: What a great library! Awesome work you have done here! Thanks so much for creating it. We use it in all of our projects.

@jnizet You discussed this topic already in https://github.com/mockk/mockk/issues/140. But since some time has gone I am curious about your opinion right now. After the official Spring Boot Kotlin guide references `springmockk`, the project got more attention (at least that is what I recognized).

From a technical point of view, it doesn't really matter but I think it could help to make a more clear statement on the state of the library and its success. Often when I talk to people it really comes down to naming and a first impression. Even when a library is excellent from a technical view, there is always some skepticism about a library that is tied to a specific user or organization about maintenance. Since `mockk` is the de-facto standard mocking library for Kotlin it may help to tied it to `mockk` or release it under the `mockk` organization.

I would love to hear your thoughts.

**Comment by jnizet** [comment]
Thanks for the kind words @pas2al.

Don't worry: I'm still willing to maintain this library. And it's free software, under an Apache 2.0 license, so anyone could fork it and release it if I failed to do it.
I understand that me being the only contributor might look scary, but the reason is, I guess, that this library is simple enough, and has reached its goal, so there isn't muh to contribute. Given the stability of both MockK and the Spring testing support now, I really don't have much work to do.

BTW, this is (unfortunately or not) the case for many open-source project. MockK itself, as far as I can see, is the result of the awesome work of Oleksiy Pylypenko.

I still feel that the proper place for the library would be the Spring Boot project, under the `org.springframework.boot.test.mock.mockk` package. I guess this could still happen some day if the usage of Kotlin and MockK with Spring Boot applications finally skyrockets (which, unfortunately, doesn't seem to be the case yet).

So the best thing to do it to use Kotlin, use MockK, use this library and spread the message I guess.

**Comment by pas2al** [comment]
Thanks so much for your update :-)
