### ISSUE TITLE
@MockkBean broke support for interfaces

### ISSUE THREAD

**Issue by hikaru-shindo** [Ninja-Squad/springmockk#43]
The update to 2.0.2 broke the support of `MockkBean` for interfaces.
It is no longer possible to inject a mock of an interface as the bean is not properly replaced.

```kotlin
@FeignClient(
    name = "customer",
    // ...
)
interface CustomerClient {
    @RequestLine("GET /customer/{customerId}")
    fun findCustomer(@Param("customerId") customerId: String): Customer
}

@SpringBootTest
class CustomerServiceTest {
    @MockkBean(relaxed = true)
    private lateinit var customerClient: CustomerClient

    @Test
    fun test() {
       every { customerClient.findCustomer(any()) } returns datajay.mk<Customer>()

      // the actual test code - will use the real bean created by feign instead of our mock.
    }
}
```

**Comment by jnizet** [comment]
Thanks for the report.

I tried to reproduce your issue using this code:

```
data class Customer(val id: String)

interface CustomerClient {
    fun findCustomer(customerId: String): Customer
}

@Component
class CustomerClientImpl : CustomerClient {
    override fun findCustomer(customerId: String): Customer {
        return Customer(customerId)
    }
}

@Component
class SomeService(val client: CustomerClient) {
    fun foo(id: String): Customer {
        return client.findCustomer(id);
    }
}

@SpringBootTest
class CustomerServiceTest {
    @MockkBean(relaxed = true)
    private lateinit var customerClient: CustomerClient

    @Autowired
    lateinit var someService: SomeService

    @Test
    fun test() {
        val customer = Customer("mocked")
        every { customerClient.findCustomer(any()) } returns customer

        val result = someService.foo("bla")
        assertThat(result).isSameAs(customer);
    }
}
```

but failed: the tests passes as expected.

Please provide a **complete minimal** example (as a separate, simple github repo, for example, or as an attached zip file I can unzip and test) reproducing the issue.

It's of course possible that I introduced an issue, but the code of springmockk is, for the most part, the same code as Spring Boot's code rewritten in Kotlin, and for MockK instead of Mockito, and the suite of automated tests is ported too. 

So I wouldn't be surprised if the issue is in fact either an issue in your code, or an issue in Spring Boot. Please try implementing the same test using Spring Boot's native support for Mockito. If you have the same issue, then that will confirm that the issue is in your code or in Spring Boot, and that SpringMockK has in fact the same behavior as Spring Boot.

**Comment by hikaru-shindo** [comment]
Thanks for the fast answer.
I added a showcase application as minimal as I could think of to this repository: https://github.com/hikaru-shindo/springmokk-mockkbean-feign-error-example

I didn't bother with actually having a working http endpoint behind it so it fails because it can't create a HTTP connection but it show the problem with the Bean not being replaced.

In reality I encountered this error while writing Pact tests but I think the overhead is not needed in the showcase (but it explains why I did not use @WebMvcTest in the example and the report)

**Comment by jnizet** [comment]
Thanks for the minimal reproduction. 👍 

I've been able to confirm that the test indeed fails with springmockk 2.0.2 but passes with 2.0.1.

The changes between these two versions however only consisted in reporting changes that have been made in the standard Mockito support of Spring Boot (quite some time ago: I had missed these changes).

So I wrote the same test using Mockito, and saw that it also fails. I then used an older version of Spring Boot (the last version that didn't include the changes that I reported in version 2.0.2 of springmockk), and saw that the same Mockito test passes using this old version.

So that's what I thought: the test is also broken using Mockito, which means that the problem has been introduced by Spring Boot, and that I simply introduced the same problem by reporting the changes made in Spring Boot.

To prove it, you can add the following test to your project:

```
package com.example.demo

import org.junit.jupiter.api.Test
import org.mockito.Mockito.`when`
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.test.mock.mockito.MockBean
import org.springframework.test.web.servlet.MockMvc
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get
import org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath
import org.springframework.test.web.servlet.result.MockMvcResultMatchers.status

@SpringBootTest
@AutoConfigureMockMvc
class CustomerControllerMockitoTest(@Autowired private val mockMvc: MockMvc) {
    @MockBean
    private lateinit var customerClient: CustomerClient

    @Test
    fun `customer can be retrieved`() {
        `when`(customerClient.findCustomer("foobar")).thenReturn(Customer(id = "testid"))

        mockMvc.perform(
            get("/foobar")
        ).andExpect(status().is2xxSuccessful)
            .andExpect(jsonPath("$.id").value("testid"))
    }
}
```

Try running it, it will fail.
Then change the Spring Boot plugin version to 2.2.6.RELEASE (in your build script), run the test again, it will pass.

So it comes from a change that has been made in Spring Boot in the 2.2.7.RELEASE version: most probably this change: 
https://github.com/spring-projects/spring-boot/commit/b9c2b7b257c0f36ee489fcc2cabda2c17cc19908.

I thus suggest you submit this issue to Spring Boot (showing them the regression in the Mockito-based test). If they acknowledge the bug and fix it, I will report the fix in SpringMockK. 

Please paste a link to the issue here, so that I can track how it goes. Don't hesitate to ping me once it's been solved or answered.

**Comment by hikaru-shindo** [comment]
Issue in spring-boot project: https://github.com/spring-projects/spring-boot/issues/22229
