### ISSUE TITLE
Unable to specify common mocking behavior in a @BeforeClass function

### ISSUE THREAD

**Issue by alwyn** [Ninja-Squad/springmockk#46]
Hi there,

The integration test I am doing is testing the following components:

- A webflux controller with a constructor injected service.
- The injected service has a single method that returns one of a set of services that are injected into its constructor.
- The controller then calls a method on the final service returned.

The following code snippets tries to explain this:
Controller construction:
```
@RestController
class HSMController(private val hsmRouterService: HSMRouterService) {
``` 
Routing service construction:
```
@Service
class DefaultHSMRouterService(
        private val lunaHSMService: LunaHSMService
) : HSMRouterService {
```
Hsm service:
```
@Service
class LunaHSMService(private val gateway: LunaClientConfiguration.LunaMessagingGateway) : HSMService {
```
Controller call:
```
            hsmRouterService.route(hsm).status(StatusRequest(hsm))
```

Now in my test I am trying to mock the router service and the hsm service like:
```
@WebFluxTest(HSMController::class)
@ExtendWith(MockKExtension::class)
class HSMControllerTests(@Autowired private val webTestClient: WebTestClient) {

    @MockkBean
    private lateinit var lunaHSMService: LunaHSMService

    @MockkBean
    private lateinit var hsmRouterService: HSMRouterService
```
I want every invocation of hsmRouterService.route to return the mocked lunaHsmService.
Each test then sets up lunaHsmService to return a specific result when called.

If I put the following in every test method:
```
        every { hsmRouterService.route(any()) } returns lunaHSMService
```
followed by my lunaHSMService mock setup, then all my tests pass.

BUT, if I try to put that piece of code in a @BeforeAll block like:
```
   @BeforeAll
    fun setup() {
        every { hsmRouterService.route(HSMProvider.LUNA) } returns lunaHSMService
    }
```
then all my tests fail with:
```
io.mockk.MockKException: no answer found for: HSMRouterService(com.tutuka.hsmgw.service.HSMRouterService#0 bean#2).route(LUNA)
```
It doesn't make a difference if I add (relaxed = true) to the lunaHsmService mock.
If I add (relaxed = true) to the hsmRouterService mock then I get a timeout in my webtestclient exchange() method as if the mocked method is not returning.  
This is the a sample of the test method
```
    @Test
    fun `Successful status`() {
//        every { hsmRouterService.route(any()) } returns lunaHSMService
        every {
            lunaHSMService.status(any())
        } returns Mono.just(
                StatusResponse(
                        HSMProvider.LUNA,
                        0,
                        mapOf(
                                "key1" to "value1",
                                "key2" to "value2"
                        )))
        webTestClient.get()
                .uri("/status?hsm=LUNA")
                .accept(MediaType.APPLICATION_JSON)
                .exchange()
                .expectStatus().isOk
                .expectHeader().contentType(MediaType.APPLICATION_JSON)
                .expectBody()
                .jsonPath("$.hsm").isEqualTo("LUNA")
                .jsonPath("$.status.key1").isEqualTo( "value1")
                .jsonPath("$.status.key2").isEqualTo("value2")
        verify {
            lunaHSMService.status(any())
        }
    }
```
I am using LifeCycle.PER_CLASS.

I do not know if this is an issue with Spring, or springmockk or mockk or me, please help me solve it.

**Comment by jnizet** [comment]
I tried to reproduce your issue, but could not: the test passes fine.

See https://github.com/jnizet/demobeforeall for a complete minimal project reproducing what you described. I made some simplifications, but overall it follows what you've described here.

Please fork this repro project, and try reproducing your issue there and spot differences with your own code.

Once you've managed to reproduce the issue, please post the URL to your reproduction, so that I can see what happens.

Notice that I've written more or less the same test with Spring Boot Mockito's native support. If the test also fails with Mockito, then you'll know that the issue is not specifically with SpringMockK.

**Comment by alwyn** [comment]
I have been able to reproduce the issue by adding a second test method.

Please take a look at: https://github.com/alwyn/demobeforeall

The good or bad news is that it also breaks with Mockito.

**Comment by alwyn** [comment]
I have just checked and @BeforeEach works instead of @BeforeAll as one would expect since it replaces my manual fixes.

One would think that @BeforeAll should work too right?

**Comment by jnizet** [comment]
MockBean has a `reset` property which has the value `AFTER`by default (see https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/mock/mockito/MockBean.html#reset--). That means that mocks created with MockBean are automatically reset after each test method (as documented).

MockkBean, similarly, has a `clear` property which has the value `AFTER`by default. So it has the exact same behavior.

Since `BeforeAll`, by definition, is only called once before running all the tests, and since the mocks are reset after each test method, the second test fails because the `hsmRouterService` starts returning null (in the case of Mockito, hence the NPE) or has no answer found anymore (in the case of MockK).

You can use `NONE` instead of `AFTER`, but that's very brittle, because what you do with the mocks in one test will have an impact on how the other tests will behave. You should simply use `BeforeEach`. There is really no good reason not to.
