### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by Numichi** [Ninja-Squad/springmockk#66]
Because Spring 2.5.x is already here and 2.6.x is coming soon, but there is no reference to these in terms of compatibility.

**Comment by jnizet** [comment]
Hi. 

I'm using it with Spring Boot 2.5.5 without issue, as I'm sure many other people do. But please tell if you find an incompatibility.
You're right that the README could be clearer about compatibility with the latest versions: when I release a new version based on the latest Spring Boot version, I specify the compatibility with that version, but I can't tell if it will be compatible with the next ones, since they don't exist yet. Most of the time, they are, because nothing in Spring Boot has changed regarding regarding the mocking support.

I will update the README
