### ISSUE TITLE
MockkClear.AFTER stops working with mockk 1.12.3

### ISSUE THREAD

**Issue by Kantis** [Ninja-Squad/springmockk#80]
After upgrading to MockK 1.12.3 we started seeing problems with using MockkClear.AFTER due to lingering recorded calls. Switching to MockkClear.BEFORE worked fine in our case. Downgrading mockk to 1.12.2 also resolved the issue.

Affects Springmockk version 3.1.1

**Comment by jnizet** [comment]
Hi @Kantis 

Can you please provide a minimal repro of the issue, preferrably as a github project that I can clone and play with? MockkClear.AFTER is the default, and all the tests of SpringMockK, and also all the tests of two real Spring Boot projects where I use SpringMockK are passing fine with MockK 1.12.3 and SpringMockK version 3.1.1.

I also created an additional test just to be sure where one test method configures a mock created with MockkBean and where another one uses that mock, and the mock is being cleared after the first test method as expected. So I don't really know what the issue can be.

That said, you made me realize that MockK 1.12.3 went from using Kotlin 1.3.x to Kotlin 1.6.x, so SpringMockK doesn't even compile anymore when using MockK 1.12.3, because it still uses Kotlin 1.4.x. So I'll probably release a version 4.0.0 of SpringMockK with MockK 1.12.3, Kotlin 1.6.10 and Spring Boot 2.6.5 ad dependencies.

**Comment by Kantis** [comment]
I'll look into creating a repro 👍🏼

**Comment by Kantis** [comment]
Tried to reproduce it in https://github.com/Kantis/springmockk-repro

I manage dto get a failing test in a similar setup. This one doesn't seem to care if it's mockk 1.12.2 or 1.12.3, unlike the one I had in my real scenario, but toggling between BEFORE/AFTER matters.

It seems that the kotest spring extension might not be invoking the Spring lifecycle correctly when using `withData`. Do you think that could be why?

**Comment by Kantis** [comment]
Okay, now I think I've figured out the reason why mockk version mattered. It seems the problem with kotest lifecycle was hidden by 1.12.2. Pushed a new commit where downgrading to 1.12.2 makes the test pass but if you change the `withArg` to just testing the argument directly it'll fail. 

So TL;DR: No problems in springmockk.

**Comment by jnizet** [comment]
Thanks @Kantis for this investigation.

**Comment by Kantis** [comment]
Kotest's Spring extension has now been adjusted to invoke `testContextManager`'s before/after between dynamic tests. Fixes the problem I was facing here.
