### ISSUE TITLE
Upgrade to the latest version of Mockk 1.13.2

### ISSUE THREAD

**Issue by alo-id** [Ninja-Squad/springmockk#87]
I would like to use the new Mockk version in my project without having to exclude it from each of my poms.

**Comment by jnizet** [comment]
Hi @alo-id 

I will eventually create a new version of SpringMockK that depends on a newer version of MockK, but you can simply specify the version of MockK that you want in your own dependencies. No need to wait for a new version of SpringMockK.

**Comment by alo-id** [comment]
I understand. I was hoping not having to do this since there is a major version release for MockK.

**Comment by MarkWilsoncom** [comment]
We´ve just upgraded to Mockk 1.13.2 and are having issues with projects which also use springmockk in unit tests.
Getting an error: java.lang.NoClassDefFoundError: io/mockk/ValueClassSupportKt

So as a workaround we have to exclude mockk from the springmockk dependency.

        <dependency>
            <groupId>com.ninja-squad</groupId>
            <artifactId>springmockk</artifactId>
            <version>${springmockk.version}</version>
            <scope>test</scope>
            
            <exclusions>
                <exclusion>
                    <groupId>io.mockk</groupId>
                    <artifactId>mockk</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by jnizet** [comment]
@MarkWilsoncom The documentation of mockk now recommends using using `io.mockk:mockk` when using gradle (which works fine in one of my projects), but `io.mockk:mockk-jvm`when using Maven. I have no clear idea why, and am not sure why there's a difference and how I should deal with this. 

Besides, [in another issue](https://github.com/Ninja-Squad/springmockk/issues/86#issuecomment-1230514149), I've been told that we would be able to use the `io.mockk:mockk` coordinates in Maven too at some time.
So I don't plan to do anything now, until the situation is clearer.

My recommendation would be to use gradle instead of Maven :-)

Feel free to open an issue on the mockk repo to know why the dependencies differ betweeb gradle and maven, and when we'll be able to use the same one everywhere.
